apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    #This defines  which pods  are going to  be represented  by this service
    #The service  becomes  a network endopoint  for either  other services 
    #or maybe external users  to connect to (ed. browser)
    app: webapp
    #mylabelname: webapp #label is completely arbitrarily but must correspond to the label specified in the respective pod.
    #release: "0-5" #"0" #another label associated with the release zero; see the first-pod file
  ports:
  - name: http  
    port: 80 #the port that receives request from other pods
    nodePort: 30080 #the port to access by using the browser
  type: NodePort #expose the port thorugh the node.

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    #This defines  which pods  are going to  be represented  by this service
    #The service  becomes  a network endopoint  for either  other services 
    #or maybe external users  to connect to (ed. browser)
    app: queue
    #mylabelname: webapp #label is completely arbitrarily but must correspond to the label specified in the respective pod.
    #release: "0-5" #"0" #another label associated with the release zero; see the first-pod file
  ports:
  - name: http  
    port: 8161 #the port that receives request from other pods
    nodePort: 30010 #the port to access by using the browser
  
  - name: endpoint #this is the endpoint for the messages
    port: 61616 #the port that receives request from other pods
    #nodePort: #not using the nodeport because we are not going to expose this to the outside world

  type: NodePort #expose the port thorugh the node.

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker #this name is added to the domain name service in kubernetes.
spec:
  selector:
    app: position-tracker
  ports:
  - name: http
    port: 8080 
    #nodePort: 30020 #only with NodePort type service.
  type: ClusterIP #NodePort #expose the port thorugh the node.


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway #this name is added to the domain name service in kubernetes.
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8080 
    #nodePort: 30020 #only with NodePort type service.
  type: ClusterIP #NodePort #expose the port thorugh the node.

  