apiVersion: apps/v1
kind: Deployment
metadata: 
  name: queue #it can be any name, not necessarily the same name of webapp specified lines behind
spec:  
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: queue #managing any pod which label is app: webapp
  template:
    ##################################################################
    #all what is behind is what must go in a simple pod - Template for pods#
    metadata:      
      labels:
        app: queue        
    spec: 
      containers:
      - name: queue #the name of the container in a Deployment really does not matter
        image: richardchesterwood/k8s-fleetman-queue:release1
    #####################################################################

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: position-simulator #it can be any name, not necessarily the same name of webapp specified lines behind
spec:  
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      name: position-simulator #managing any pod which label is app: webapp
  template:
    ##################################################################
    #all what is behind is what must go in a simple pod - Template for pods#
    metadata:      
      labels:
        name: position-simulator
    spec: 
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
    #####################################################################

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: position-tracker #it can be any name, not necessarily the same name of webapp specified lines behind
spec:  
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker #managing any pod which label is app: webapp
  template:
    ##################################################################
    #all what is behind is what must go in a simple pod - Template for pods#
    metadata:      
      labels:
        app: position-tracker
    spec: 
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
    #####################################################################

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-gateway #it can be any name, not necessarily the same name of webapp specified lines behind
spec:  
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway #managing any pod which label is app: webapp
  template:
    ##################################################################
    #all what is behind is what must go in a simple pod - Template for pods#
    metadata:      
      labels:
        app: api-gateway
    spec: 
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
    #####################################################################

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp #it can be any name, not necessarily the same name of webapp specified lines behind
spec:  
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: webapp #managing any pod which label is app: webapp
  template:
    ##################################################################
    #all what is behind is what must go in a simple pod - Template for pods#
    metadata:      
      labels:
        app: webapp
    spec: 
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
    #####################################################################    